000a = "Front Cover"
# 000b (Inside Front Cover)

# 001 (Title)
002 = "Copyright"
003 = "Personal Note"
# 004 (Blank)
007 = "Contents"
# 008 (Blank)
009 = "Introduction"
# 010 (Blank)
011 = "Foreword"
014 = "Music Transcriber's note"
015 = "Index of Song Titles"

019 = "Abahainn An T-Sluaigh"
022 = "A Dh'Innse Na Firinn"
024 = "Air A' Chuan"
026 = "Air An Tràigh"
029 = "Alba"
032 = "All Things Must Change"
034 = "Always The Winner"
036 = "Amazing Things"
039 = "An Cuibhle Mòr"
044 = "An Ròs"
046 = "An T-Iasgair"
048 = "An Toll Dubh"
050 = "An Ubhal As Àirde"
053 = "Àrd"
057 = "Big Sky"
060 = "Canada"
062 = "Cearcal A' Chuain"
064 = "Chi Mi'n Geamhradh"
066 = "Cho Buidhe Sa Bha I Riabh"
068 = "City of Lights"
070 = "Clachan Uaine"
072 = "Cnoc na Feille"
074 = "Cum 'Ur N'aire"
076 = "Dà Mhìle Bliadhna"
081 = "Dance Called America"
084 = "Day In A Boat"
086 = "Dreamfields"
088 = "Dùisg Mo Rùin"
090 = "Dust"
093 = "Edge of the World"
096 = "Èirinn"
098 = "Every River"
101 = "Fichead Bliadhna"
105 = "Flower Of The West"
109 = "Foghar Nan Eilean '78"
112 = "Forever Eyes of Blue"
114 = "For The Love Of Alison"

116 = "Fuaim A' Bhlàir"
119 = "Going Home"
122 = "Harvest Moon"
124 = "Headlights"
126 = "Healer In Your Heart"
129 = "Hearthammer"
132 = "Hearts of Olden Glory"
134 = "I'll Keep Coming Home"
136 = "In Search Of Angels"
138 = "Life Is"
140 = "Lifeline"
142 = "Lighthouse"
144 = "Mairi"
146 = "Maymorning"
149 = "Meadhan Oidhche Air An Acairseid"
152 = "Morning Tide"
154 = "Move A Mountain"
156 = "Nach Neonach Neisd A Tha E"
158 = "Na H-Uain A's T-Earrach"
160 = "News From Heaven"
163 = "Nothing But The Sun"
166 = "O Cho Meallt"
168 = "Only The Brave"
170 = "Òran"
172 = "Our Earth Was Once Green"
174 = "Pòg Aon Oidhche Earraich"
176 = "Precious Years"
178 = "Pride Of The Summer"
180 = "Protect And Survive"
182 = "Ravenscraig"
184 = "Recovery"
186 = "Ribhinn Donn"
188 = "Ribhinn O"
190 = "Road And The River"
192 = "Rocket To The Moon"
194 = "Rubh Nan Cudaigean"
196 = "Saints of The Soil"
198 = "Satellite Flood"
201 = "Sguapan Arbhair"

205 = "Sìol Ghoraidh"
209 = "Skye"
212 = "Smalltown"
215 = "Song Of The Earth"
218 = "Sràidean Na Roinn-Eòrpa"
220 = "Stepping Down The Glory Road"
222 = "'s Tu Mo Leannan/Nightfall On Marsco"
224 = "Sunndach"
226 = "Tear Down These Walls"
228 = "Thairis Air A' Ghleann"
230 = "That Final Mile"
232 = "That Other Landscape"
234 = "The Apple Came Down"
236 = "The Cutter"
238 = "The Dancing Floor"
240 = "The Everlasting Gun"
242 = "The Fisherman"
244 = "The Ferry"
247 = "The Greatest Flame"
250 = "The Message"
252 = "The Mighty Atlantic"
254 = "The Old Boys"
256 = "The Only Rose"
258 = "The Summer Walkers"
261 = "The Wedding"
265 = "The Wire"
268 = "The Work Song"
270 = "Things That Are"
272 = "This Beautiful Pain"
276 = "This Is Not A Love Song"
278 = "This Time Of Year"
280 = "Tillidh Mi"
282 = "Tìr A' Mhurain"
284 = "Tir An Airm"
286 = "Travellers"
288 = "Wonderful"
290 = "Worker For The Wind"
292 = "World Appeal"

294 = "Credits"
295 = "Acknowledgements"
296 = "Epilogue"

# 297a (Inside Back Cover)
297b = "Back Cover"
